/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ascii.lands;

public class App {

    public static void main(String[] args) {
        Donkey donkey = new Donkey();
        donkey.say("hello");
    }
}
